spring.application.name=desarrollo
spring.datasource.url=jdbc:postgresql://localhost:5433/Muvu
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
server.port = 8081


#Don't touch my apis Cristhian
stripe.api.key=${STRIPE_SECRET_KEY}
google.maps.api.key=${GOOGLE_MAPS_API_KEY}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}