spring.application.name=desarrollo
stripe.api.key=${STRIPE_SECRET_KEY}
spring.datasource.url=jdbc:postgresql://localhost:5433/Muvu
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
server.port = 8081
